language: csharp
solution: AlienEngine.sln
install:
  - nuget restore AlienEngine.sln
  - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AlienEngine.sln
  - mono ./testrunner/NUnit.Console.3.8.0/nunit3-console.exe ./AlienEngine.UnitTest/bin/Release/AlienEngine.UnitTest.dll