language: csharp
solution: AlienEngine.sln
install:
  - nuget restore AlienEngine.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AlienEngine.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./AlienEngine.UnitTest/bin/Release/AlienEngine.UnitTest.dll